### ISSUE TITLE
Token simulation for inclusive gateways

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/bpmn-js-token-simulation#122] opened 2022-10-25 15:06 UTC
__Is your feature request related to a problem? Please describe__

Currently, users can't run token simulation for inclusive gateways.

![Bildschirmfoto 2022-10-25 um 17 05 15](https://user-images.githubusercontent.com/56470362/197810766-cbb299b3-794a-4b51-92ad-8f09d9fbef56.png)

This ways raised by a participant during the 8.1 release webinar.

__Describe the solution you'd like__

Allow token simulation for inclusive gateways (allow the token to split in selected sequence flows)

**Comment by nikku** [comment] 2022-10-26 10:31
Seems to be a duplicate of https://github.com/bpmn-io/bpmn-js-token-simulation/issues/88, am I correct? Inclusive gateway join is not "computable", hence we've not implemented it (yet).

There is a PR in in flight to attempt adding it (https://github.com/bpmn-io/bpmn-js-token-simulation/pull/110).

**Closed** 2022-10-28 07:24 UTC
Labels: duplicate, enhancement
