### ISSUE TITLE
End Event sometimes behaves as a Terminate Event

### ISSUE THREAD

**Issue by rajgoel** [bpmn-io/bpmn-js-token-simulation#59] opened 2021-01-15 13:37 UTC
__Describe the Bug__

Sometimes (but not always) an End Event behaves like a Terminate Event. In other words the End Event removes other tokens still running.

__Steps to Reproduce__

_See also https://github.com/bpmn-io/bpmn-js-token-simulation/issues/59#issuecomment-762819458 for attached screen captures._

In the "ATM Transaction" example provided, it is possible to trigger the non-interrupting timer event for the "Cash Withdrawal" activity. 

If the Timer Event is triggered very early and the End Event following the "Timeout" activity is reached before the "Cash Withdrawal" is completed, the process terminates:

```
14:22:22:160 ATM Transaction Needed
14:22:22:164 Process 1 started
14:22:23:452 Insert Card
14:22:24:735 Select Interaction
14:22:26:16 Selected Interaction? Cash Withdrawal
14:22:27:284 Select Amount
14:22:28:567 Starting Subprocess
14:22:28:571 Cash Amount Selected
14:22:28:573 Subprocess 2 started
14:22:31:66 Timeout
14:22:31:133 Prepare Cash
14:22:31:143 Charge Account
14:22:32:351 End Event
14:22:32:355 Process 1 finished
```

__Expected Behavior__

If the Timer Event  is triggered later, e.g. after "Issue Money" is conducted, the End Event following the "Timeout" activity is reached after the "Cash Withdrawal" is completed. In this case, the process does not terminate and behaves as expected:

```
14:25:05:704 ATM Transaction Needed
14:25:05:706 Process 1 started
14:25:06:989 Insert Card
14:25:08:269 Select Interaction
14:25:09:553 Selected Interaction? Cash Withdrawal
14:25:10:836 Select Amount
14:25:12:120 Starting Subprocess
14:25:12:124 Cash Amount Selected
14:25:12:126 Subprocess 2 started
14:25:14:688 Charge Account
14:25:14:712 Prepare Cash
14:25:17:287 Issue Money
14:25:18:577 Cash Issued
14:25:18:582 Subprocess 2 finished
14:25:19:187 Timeout
14:25:20:469 End Event
14:25:22:125 Cash Withdrawn
14:25:23:403 Check For Further Interactions
14:25:26:31 No Further Interaction Requested
14:25:27:303 Return Card
14:25:28:586 ATM Transaction Finsihed
14:25:28:588 Process 1 finished
```

The process should only be terminated on an End Event if there are no other tokens in the system.

__Environment__

I used the release 0.11.1 and deployed the app on my webhost (after creating it with `npm install --save-dev webpack`).

**Comment by nikku** [comment] 2021-01-19 12:24
Could you share a screen cast that shows the behavior you describe? As you indicated it seems to be a timing related issue and a screen capture allows us to easier reproduce it.

**Comment by rajgoel** [comment] 2021-01-19 12:47
Here are the screencasts:

This is how it is supposed to work:
![Correct](https://user-images.githubusercontent.com/4448455/105036252-87fe1980-5a5c-11eb-8daa-e0a0e9f0cd62.gif)

This is how it works if the subprocess is not completed when the end event is reached (leads to premature termination):
![Wrong](https://user-images.githubusercontent.com/4448455/105036259-89c7dd00-5a5c-11eb-90e6-29b72ca2271d.gif)

**Comment by nikku** [comment] 2021-05-07 21:57
Fixed via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/65.

**Closed by nikku** 2021-05-07 21:57 UTC
Labels: backlog, bug
