### ISSUE TITLE
Event-based gateway triggers multiple message events.

### ISSUE THREAD

**Issue by timKraeuter** [bpmn-io/bpmn-js-token-simulation#103] opened 2022-01-26 13:39 UTC
__Describe the Bug__

An event-based gateway with two following message catch events leads to activation of both of them when a message is incoming to either one of them.
In screenshots:
![image](https://user-images.githubusercontent.com/21026858/151172207-42af60e2-81da-49ae-80ee-627a57b9e881.png)
Leads to:
![image](https://user-images.githubusercontent.com/21026858/151172258-9d0e1923-cd72-425e-b4ae-3949a318ada9.png)

I think this bug is relatively new. Last week, I did not notice it when I executed my models (Maybe it was introduced by the changes on 25.01.2022).

__Steps to Reproduce__

1. Import the provided BPMN model ([event_gateway_bug.txt](https://github.com/bpmn-io/bpmn-js-token-simulation/files/7942101/event_gateway_bug.txt)).
2. Start the process with the event-based gateway.
3. Start the process with the message send event.

It also happens if you trigger one of the message catch events by hand.

It also happens for other catch events following a gateway. All events of the same type are triggered in case one of   them is triggered (see: [event_gateway_bug_other_scenarios.txt](https://github.com/bpmn-io/bpmn-js-token-simulation/files/7942144/event_gateway_bug_other_scenarios.txt)).

__Expected Behavior__

Only the intermediate event which receives the messages should be activated.

__Environment__

- Host (Browser/Node version), if applicable: Chrome and Firefox.
- OS: Windows 10
- Library version: Current deployment: https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html

**Comment by nikku** [comment] 2022-01-26 13:51
The bug is indeed fairly new. Thanks for reporting.

Both events configured actually reference the same message (no message ref):

```
<bpmn:intermediateCatchEvent>
  <bpmn:messageEventDefinition id="MessageEventDefinition_1goizu1" />
</bpmn:intermediateCatchEvent>
```

This means both listen to the same message => message arrives => message triggered for both.

A simple way to fix this on your end is to make the event definitions actually reference  different messages.

**Comment by timKraeuter** [comment] 2022-01-26 13:55
Thanks for the quick reply, workaround and impressive simulator.

I just added another file. It does not only happen for message events.
Might be the same root cause.

ons. 26. jan. 2022, 14:51 skrev Nico Rehwaldt ***@***.***>:

**Comment by nikku** [comment] 2022-01-26 13:56
It is the same root cause. If no error, message, escalation is referenced for two events these two events are treated as _being the same_ by the simulator.

**Comment by timKraeuter** [comment] 2022-01-27 09:19
Thanks, I can confirm that your suggested fix to reference messages works!

**Comment by nikku** [comment] 2022-01-29 07:38
I've added a properties panel to the built-in example (https://github.com/bpmn-io/bpmn-js-token-simulation/pull/104); this will at least give you the chance to introspect your events and see that the same events are being re-used.

Closing this issue and waiting for further feedback.

**Comment by nikku** [comment] 2022-01-29 12:34
After further consideration I decided to address this issue. Turns out having multiple start events would otherwise also start a process multiple times.

![capture CjLcBF_optimized](https://user-images.githubusercontent.com/58601/151661187-404e3dc3-b241-48be-9b1e-93680bf6d591.gif)

**Comment by timKraeuter** [comment] 2022-01-29 13:52
I think it makes sense to address it. Especially after your new example!

**Closed** 2022-01-29 14:33 UTC
Labels: bug, needs review
